version: '2'

services:
  proxy: 
    build: ./nginx
    links:
      - bibcat:bibcat
    ports:
      - "80:80"
      - "443:443"
    restart: always

  bibcat:
    build: .
    ports:
     - "5000:5000"
    restart: always
